<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>memcadmin</title>		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="">
	    <meta name="author" content="">
	    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<style type="text/css">
		body {
			padding-top: 60px;
			padding-bottom: 40px;
		}
		footer {
			color: gray;
			font-size: 10px;
		}
		</style>
		<link href="/lib/twitter-bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <a class="brand" href="/">memcadmin</a>
	          <div class="nav-collapse collapse">
	            <ul class="nav">
		            <li><a href="/overview">Overview</a></li>
		            <?php if ($this->_structure): ?>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cluster <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<?php foreach($this->_structure as $cluster): ?>
									<li><a href="/cluster/<?=$cluster->getName()?>"><?=$cluster->getName()?></a></li>
								<?php endforeach; ?>
							</ul>
						</li>
		          	<?php endif; ?>
	            </ul>	            
	          </div>
	        </div>
	      </div>
	    </div>
	    <div class="container">
			<?=$ob_content?>
			<hr>
			<footer>
				<p>memcadmin, by Christoph Slamanig, based on parts of Harun Yayli's memcache.php, CSS by twitter.bootsrap.</p>
			</footer>
		</div>
		<script src="/js/jquery-1.8.1.min.js"></script>
		<script src="/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
	</body>
</html>