<style>
.right {
	text-align: right !important;
}
</style>

<?php if ($this->_view->items): ?>

	<h1><?=$this->_view->clusterName?> : <?=$this->_view->nodeName?></h1>

	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav">
				<li><a href=".?a=slabs&amp;c=<?=$this->_view->clusterName?>&amp;n=<?=$this->_view->nodeName?>">Slabs</a></li>
				<li<?php if(!$this->_view->requestSlabId): ?> class="active"<?php endif; ?>><a href="#">All items</a></li>
			</ul>
		</div>
	</div>

	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th width="10%">Slab ID</th>
				<th width="60%">Key</th>
				<th width="30%">Size</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->_view->items as $item): ?>
			<tr>
				<td><?=$item['slabId']?></td>
				<td><?=$item['key']?></td>
				<td><?=$item['size']?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

<?php endif; ?>