<?php if ($this->_view->slabs): ?>

	<h1><?=$this->_view->clusterName?> : <?=$this->_view->nodeName?></h1>

	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav">
				<li class="active"><a href="#">Slabs</a></li>
			</ul>
		</div>
	</div>

	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th width="25%">Slab ID</th>
				<th width="25%">Item count</th>
				<th width="25%">Age</th>
				<th width="25%">Evicted</th>       
			</tr>
	  </thead>   
	  <tbody>
		<?php foreach($this->_view->slabs['items'] as $slabId => $slab): ?>
			<tr>
				<td><?=$slabId?></td>
				<td class="center"><?=$slab['number']?></td>
				<td class="center"><?=$slab['age']?></td>
				<td class="center"><?=$slab['evicted']?></td>                                 
			</tr>
		<?php endforeach; ?>
			<tr>
				<td><b>All</b></td>
				<td class="center"><b><?=$this->_view->slabs['count']?></b></td>
				<td class="center">-</td>
				<td class="center">-</td>                                 
			</tr>
	  </tbody>
	</table>

<?php endif; ?>